import localFont from "next/font/local";
import "./globals.scss";

const clayo = localFont({
  src: [
    {
      path: "../../public/fonts/CLAYO-Semibold.ttf",
      weight: "600",
      style: "semibold"
    }
  ],
  variable: "--font-clayo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clayo.className}>{children}</body>
    </html>
  );
}
